name: docs

on:
    # æ¯å½“ push åˆ° main åˆ†æ”¯æ—¶è§¦å‘éƒ¨ç½²
    push:
        branches: [master]
    # æ‰‹åŠ¨è§¦å‘éƒ¨ç½²
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              # - uses: actions/checkout@v2.3.1
              with:
                  # â€œæœ€è¿‘æ›´æ–°æ—¶é—´â€ ç­‰ git æ—¥å¿—ç›¸å…³ä¿¡æ¯ï¼Œéœ€è¦æ‹‰å–å…¨éƒ¨æäº¤è®°å½•
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  # é€‰æ‹©è¦ä½¿ç”¨çš„ pnpm ç‰ˆæœ¬
                  version: 8
                  # ä½¿ç”¨ pnpm å®‰è£…ä¾èµ–
                  run_install: true

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  # é€‰æ‹©è¦ä½¿ç”¨çš„ node ç‰ˆæœ¬
                  node-version: 18
                  # ç¼“å­˜ pnpm ä¾èµ–
                  cache: pnpm

            # è¿è¡Œæ„å»ºè„šæœ¬
            #   - name: Install and Build ğŸ”§
            #   run: |
            #       npm install
            #       npm run build
            #   env:
            #       NODE_OPTIONS: "--max_old_space_size=4096"
            - name: Build VuePress site
              #    run: |
              #       pnpm install
              #       pnpm run build
              run: pnpm run build

            # æŸ¥çœ‹ workflow çš„æ–‡æ¡£æ¥è·å–æ›´å¤šä¿¡æ¯
            # @see https://github.com/crazy-max/ghaction-github-pages
            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
                  target_branch: gh-pages
                  # éƒ¨ç½²ç›®å½•ä¸º VuePress çš„é»˜è®¤è¾“å‡ºç›®å½•
                  build_dir: .vuepress/dist
              env:
                  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKENone }}
